import { Inter } from 'next/font/google'
//import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Turing ReactJS 7th Batch',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
